application_data_volume:
    image: 'busybox'
    tty: true
    restart: 'always'
    container_name: 'application_data_volume'
    volumes:
      - './www/:/var/www/'

php-fpm:
    build: 'php-fpm/php70'
    container_name: 'php-fpm'
    expose:
        - '9000'
    volumes_from:
        - 'application_data_volume'
    restart: always

php-cli:
    build: 'php-cli/php70'
    container_name: 'php-cli'
    volumes:
        - './shared/composer/:/root/.composer/'
    working_dir: /var/www

nginx:
    build: 'nginx'
    container_name: 'nginx'
    links:
        - 'php-fpm'
    ports:
        - '80:80'
        - '443:443'
    restart: 'always'
    volumes:
        - './shared/ssl/:/etc/nginx/ssl/:ro'
    volumes_from:
        - 'application_data_volume'
